CFLAGS = -Wall -Wdeclaration-after-statement -Ddebug
CXXFLAGS = -Wall #-Ddebug
LDLIBS = -lm

vektoren: vektoren.cpp Vektor.o CPUtime.o 
Vektor.o: Vektor.cpp Headers/Vektor.h
CPUtime.o: Headers/CPUtime.h CPUtime.cpp
